name: projeto_p1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.4

flutter_native_splash:
  color: "#F8F4E4"  # Cor de fundo da splash screen
  image: web/icons/logo-inicial.png  # Caminho da imagem do logo
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/capas/